### ISSUE TITLE
mnist mlp.jl: ERROR: scalar getindex is disallowed

### ISSUE THREAD

**Issue by philtomson** [FluxML/model-zoo#212]
I'm trying to run the vision/mnist/mlp.jl example and I get:

ERROR: scalar getindex is disallowed (at line 16)

This is apparently due to the following at line 8:

`    CuArrays.allowscalar(false)`

If I change that to: 

`    CuArrays.allowscalar(true)`

It will work, but I get the following warning:
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`

This is with Julia 1.3.1
 pkg> status
    Status `~/.julia/environments/v1.3/Project.toml`
  [3895d2a7] CUDAapi v3.1.0
  [c5f51814] CUDAdrv v6.0.0
  [be33ccc6] CUDAnative v2.10.2
  [3a865a2d] CuArrays v1.7.3
  [587475ba] Flux v0.10.3

**Comment by CarloLucibello** [comment]
this is probably due to some onehot matrices that need to be sent to cpu when computing accuracies. This will be fixed in https://github.com/FluxML/model-zoo/pull/210

This repo is in the process of being revamped. Take a look at https://github.com/FluxML/model-zoo/blob/master/vision/lenet_mnist/lenet_mnist.jl for a recently updated example

**Comment by joostveenema** [comment]
Seems fixed, the current version runs fine with CUDA.allowscalar(false)
