### ISSUE TITLE
DCGAN implementation??

### ISSUE THREAD

**Issue by rutvij-25** [FluxML/model-zoo#310]
I have seen the discriminator and generator in DCGAN consists of only Conv layers and not Dense layers

**Comment by CarloLucibello** [comment]
> I have seen the discriminator and generator in DCGAN consists of only Conv layers and not Dense layers

This is not true, discriminators have a final dense layer
https://github.com/FluxML/model-zoo/blob/7d2a4253bd9cb1f6ff88926750724aec67251f08/vision/dcgan_mnist/dcgan_mnist.jl#L46
The generator instead has to be fully convolutional since it produces images

btw, `DCGAN implementation??` is not an informative issue title.
